# Generated by Django 5.2.5 on 2025-09-15 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blogpost_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
